server:
  port: ${PORT:0}

spring:
  application:
    name: api-catalog
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      username: usr-inscription-mongo
      password: pwd-inscription-mongo
      database: inscription-dev-mongo
      port: 27017
      host: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Esto expone todos los endpoints de Actuator
  endpoint:
    health:
      show-details: always # Muestra detalles completos en el endpoint /actuator/health


logging:
  level:
    org.springframework.web: DEBUG
    com.my.package: DEBUG

resilience4j:
  retry:
      configs:
        default:
          max-retry-attempts: 3
          wait-duration: 1s
          retry-exceptions:
            - java.io.IOException
            - java.net.SocketTimeoutException
  circuitbreaker:
    instances:
      clientCatalog:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
