server:
  port: ${PORT:0}

spring:
  application:
    name: api-serie
  zipkin:
    base-url: http://localhost:9411
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*" # Esto expone todos los endpoints de Actuator
  endpoint:
    health:
      show-details: always # Muestra detalles completos en el endpoint /actuator/health

info:
  app:
    name: "API-SERVICE"
    description: Description
    version: Version

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
