server:
  port: ${PORT:0}

spring:
  application:
    name: api-serie
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://usr-inscription-mongo:pwd-inscription-mongo@localhost:27017/inscription-dev-mongo?authSource=admin
      username: usr-inscription-mongo
      password: pwd-inscription-mongo
      database: inscription-dev-mongo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*" # Esto expone todos los endpoints de Actuator
  endpoint:
    health:
      show-details: always # Muestra detalles completos en el endpoint /actuator/health

info:
  app:
    name: "API-SERVICE"
    description: Description
    version: Version

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

