server:
  port: ${PORT:8761}

spring:
  application:
    name: eurekaServer
  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
