server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-catalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**





